<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wpisz co najmniej jedn z poniszych da_e6a9c4</name>
   <tag></tag>
   <elementGuidId>8ef0725d-20a2-4ab9-a595-cb3c6dba0239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#person_imie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='person_imie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecd8617b-5129-4c6d-b839-b083e977af92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-group</value>
      <webElementGuid>e37fecdc-6208-4767-96ca-d8462d642456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Imię</value>
      <webElementGuid>f8e24315-3394-4a94-952f-3253ca963a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0bdde40f-e309-4b87-8a88-df978501264f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>person[imie]</value>
      <webElementGuid>f24e13fc-f314-487a-bdf0-037adf20079e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>person_imie</value>
      <webElementGuid>5ea2baa1-6cd6-43cb-8f5b-21f0571ed81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;person_imie&quot;)</value>
      <webElementGuid>ad056114-df45-4590-b7a6-a45d0b7e0b38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='person_imie']</value>
      <webElementGuid>3d873fd0-5f10-48e1-82c2-0d2201ad1da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search2']/form/div/div/div/div/div/input</value>
      <webElementGuid>6b2b994a-876c-43bf-ab5d-ae88d9b9f8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>3902ac8f-34db-4b0b-9b26-e2b37780e43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Imię' and @type = 'text' and @name = 'person[imie]' and @id = 'person_imie']</value>
      <webElementGuid>32a587d9-fd57-46a0-a99c-69a4f504bb34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
