<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wpisz co najmniej jedn z poniszych da_d007f2</name>
   <tag></tag>
   <elementGuidId>1acae1bb-e099-4f93-9d12-00000ebd6083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#person_nazwisko</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='person_nazwisko']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cd84ecc-ccbc-4d90-852f-60d42da31669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-group</value>
      <webElementGuid>78ef02eb-3fe1-489c-af24-e1a165acb592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nazwisko</value>
      <webElementGuid>7d4948cf-e5ae-4743-a86d-1d772d05450b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>134e0f12-118d-4373-b297-328d392e9f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>person[nazwisko]</value>
      <webElementGuid>ca7b7a56-20ab-46b8-b423-d39d06db236f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>person_nazwisko</value>
      <webElementGuid>ed3f2668-d30a-4254-899c-0db3523ce7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;person_nazwisko&quot;)</value>
      <webElementGuid>e30efc91-0e8c-4ef1-b4c0-6d6eaedcee3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='person_nazwisko']</value>
      <webElementGuid>7c485382-49ef-48c0-9fc8-3f0b0af64a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search2']/form/div/div/div/input</value>
      <webElementGuid>0e082f86-176b-4c89-907b-ce8c4f6c333e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>2beeb388-c78c-4a45-859e-84bf8eb89860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nazwisko' and @type = 'text' and @name = 'person[nazwisko]' and @id = 'person_nazwisko']</value>
      <webElementGuid>607ba699-b29b-4daa-8a25-dc0c375dfebe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
